### PR TITLE
Suppport scrolling numbers up and down, add timeout prop, update readme, and more

### PR DESCRIPTION
**Pull request by KevinVandy**
- add 1 second default timeout
- add support for toLocaleString()
- rewrite useEffect to support number going up or down
- remove fallback for simplicity
- update readme with multiple examples

### CODE REVIEW

**Comment by KevinVandy** [comment]
Hey @sbimochan , I was looking for a library just like this and found your repo. It almost worked for what I needed, but had some issues. I fixed all those issues, but also removed the fallback prop since it complicated the code a bit and was not useful to me. But I can add it back if it is important for this package overall.

**Comment by KevinVandy** [comment]
I ended up making way more changes and rewrote in TSDX. I'll close since it is now so different that your original repo.

**Comment by sbimochan** [comment]
No, it's fine. I was gonna rewrite too this weekend.

**Comment by KevinVandy** [comment]
@sbimochan I'm mostly done editing my own repo for now. You can see static examples of the changes I made in a storybook here
 https://kevinvandy.github.io/react-number-scroller/?path=/docs/
You could accept this pull request. But then change all of the package names back to "number-scroller" instead of "react-number-scroller" if you want this full tsdx rewrite.

**Pull request merged**
